### ISSUE TITLE
problem importing wntr into python

### ISSUE THREAD

**Issue by kalebsm** [USEPA/WNTR#120]
I am trying to run some code that imports wntr and I get this import error: (ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by …)). I am working in a virtual environment that I have downloaded all the required dependent packages. I cannot seem to track down how to fix this, though I have tracked the libstdc++.so.6 thing to the following website which sites a similar issue (http://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.what) but does not give a clear solution to my problem if any.

How might I fix this?

**Comment by michaelbynum** [comment]
@kalebsm Can you please provide the operating system you are working on, the python version you are using, and a full stack trace for the error you are getting?

**Comment by kalebsm** [comment]
@michaelbynum I am working on Red Hat Enterpirse Linux 7.4, with python3.6. Here is the trace:

Traceback (most recent call last):
  File "/[...]/venv/lib/python3.6/site-packages/wntr/sim/aml/evaluator.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/[...]/venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /[...]/venv/lib/python3.6/site-packages/wntr/sim/aml/_evaluator.cpython-36m-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/[...]/venv/lib/python3.6/site-packages/wntr/__init__.py", line 3, in <module>
    from wntr import morph
  File "/[...]/venv/lib/python3.6/site-packages/wntr/morph/__init__.py", line 13, in <module>
    from wntr.morph.skel import skeletonize
  File "/[...]/venv/lib/python3.6/site-packages/wntr/morph/skel.py", line 10, in <module>
    from wntr.sim.core import WNTRSimulator
  File "/[...]/venv/lib/python3.6/site-packages/wntr/sim/__init__.py", line 5, in <module>
    from wntr.sim.core import WaterNetworkSimulator, WNTRSimulator
  File "/[...]/venv/lib/python3.6/site-packages/wntr/sim/core.py", line 1, in <module>
    import wntr.sim.hydraulics
  File "/[...]/venv/lib/python3.6/site-packages/wntr/sim/hydraulics.py", line 14, in <module>
    from wntr.sim import aml
  File "/[...]/venv/lib/python3.6/site-packages/wntr/sim/aml/__init__.py", line 2, in <module>
    from .aml import Model, ParamDict, VarDict, ConstraintDict, Constraint
  File "/[...]/venv/lib/python3.6/site-packages/wntr/sim/aml/aml.py", line 3, in <module>
    from .evaluator import Evaluator
  File "/[...]/venv/lib/python3.6/site-packages/wntr/sim/aml/evaluator.py", line 17, in <module>
    _evaluator = swig_import_helper()
  File "/[...]/venv/lib/python3.6/site-packages/wntr/sim/aml/evaluator.py", line 16, in swig_import_helper
    return importlib.import_module('_evaluator')
  File "/[...]/venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_evaluator'

**Comment by RedISeb** [comment]
Im using Python 3.7 on Win 10 and get nearly the same error: _ModuleNotFoundError: No module named '_evaluator'_
But surprisingly when I run a wntr example within the anaconda environment it works without any problems or error messages

**Comment by dbhart** [comment]
I have started trying to set up tests for Python 3.8 and have similarly seen this issue. It has to do with the linking between numpy and the aml simulation module in WNTR. I don’t know if Michael has any ideas on what to do for this. Using anaconda is ensuring that the libraries match which is why it works in the anaconda environment; the binaries are built with conda-forge.

**Comment by afmurillo** [comment]
Hello, I have the same issue. My environment is a little more rough, this is a mininet virtual machine running Ubuntu Xenial and python 2.7, I'm trying to import using ipython

**Comment by michaelbynum** [comment]
@kalebsm @RedISeb @afmurillo Could you also please mention how you installed WNTR? I apologize for the trouble. I will try to get this fixed ASAP.

**Comment by michaelbynum** [comment]
@afmurillo Sorry, WNTR no longer supports Python 2.7. Please see the release notes at https://wntr.readthedocs.io/en/latest/whatsnew.html#v0-2-1-aug-13-2019.

**Comment by michaelbynum** [comment]
Sorry @kalebsm, but I have a few more questions. 

1. How did you create your virtual environment (venv, condo, etc.)? It looks like venv, but I want to be sure.

2. How did you install WNTR?

3. What output do you get when you enter the python console from a terminal? For example, I get
$ python
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by RedISeb** [comment]
@michaelbynum I simply used pip install wntr

**Comment by michaelbynum** [comment]
@RedISeb Can you also provide the full stack trace?

**Comment by michaelbynum** [comment]
While I am working on fixing this, I recommend installing WNTR with conda.

**Comment by RedISeb** [comment]
@michaelbynum ofc
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wntr\sim\aml\evaluator.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\seb\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wntr.sim.aml._evaluator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\seb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wntr\__init__.py", line 3, in <module>
    from wntr import morph
  File "C:\Users\seb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wntr\morph\__init__.py", line 13, in <module>
    from wntr.morph.skel import skeletonize
  File "C:\Users\seb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wntr\morph\skel.py", line 10, in <module>
    from wntr.sim.core import WNTRSimulator
  File "C:\Users\seb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wntr\sim\__init__.py", line 5, in <module>
    from wntr.sim.core import WaterNetworkSimulator, WNTRSimulator
  File "C:\Users\seb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wntr\sim\core.py", line 1, in <module>
    import wntr.sim.hydraulics
  File "C:\Users\seb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wntr\sim\hydraulics.py", line 14, in <module>
    from wntr.sim import aml
  File "C:\Users\seb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wntr\sim\aml\__init__.py", line 2, in <module>
    from .aml import Model, ParamDict, VarDict, ConstraintDict, Constraint
  File "C:\Users\seb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wntr\sim\aml\aml.py", line 3, in <module>
    from .evaluator import Evaluator
  File "C:\Users\seb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wntr\sim\aml\evaluator.py", line 17, in <module>
    _evaluator = swig_import_helper()
  File "C:\Users\seb\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wntr\sim\aml\evaluator.py", line 16, in swig_import_helper
    return importlib.import_module('_evaluator')
  File "C:\Users\seb\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_evaluator'

**Comment by jorgeps86** [comment]
I'm trying to use WNTR on my laptop. Windows 10. Python 3.7.2
When importing WNTR to the Jupyter Notebook, I got the error
"ModuleNotFoundError: No module named 'wntr.sim.aml._evaluator'"

However, when I use the command prompt and install WNTR using pip, I got:
"Requirement already satisfied: wntr in c:\python\lib\site-packages (0.2.1)"

Does anyone know how to solve this problem?
PD. Conda did not find WNTR

Thanks in advance!

**Comment by afmurillo** [comment]
> @afmurillo Sorry, WNTR no longer supports Python 2.7. Please see the release notes at https://wntr.readthedocs.io/en/latest/whatsnew.html#v0-2-1-aug-13-2019.

I see. the solution I found was using virtual environments in python. So I can run python 3.7 for WNTR and 2.7 for all the other modules we have. 
Probably that solution will also work for other people issues

**Comment by michaelbynum** [comment]
@jorgeps86 Sorry, when installing WNTR with Conda, you need

```
conda install -c conda-forge wntr
```

**Comment by jorgeps86** [comment]
Hi @michaelbynum and thank you for the quick response. Unfortunately, after using conda install -c conda-forge wntr, the package seems to be installed but the problem when importing it from jupyter notebook persists: ModuleNotFoundError.

Would you let me know if you have any ideas?
Thank you for your time.

**Comment by dbhart** [comment]
Hi @jorgeps86 , my suspicion is that the jupyter you are using isn't a conda installed version, or that jupyter is coming from a different conda environment. That would cause jupyter to not be able to find the module, because it is looking at a different PYTHON_LIB location from the conda install of WNTR.

**Comment by jorgeps86** [comment]
You are completely right. I had installed Python twice by Anaconda and directly. I uninstalled the latter and now WNTR can be imported without any issues. Thank you @dbhart  !

**Comment by dbhart** [comment]
@jorgeps86 I am glad that it is working! We will update the install instructions to mention that using conda and Python.org simultaneously can (will) cause problems.

We are working to update the installation instructions for the folks that are finding issues with Linux environments. For those folks, like @kalebsm , we are working to update the install to describe how to build the binaries locally, instead. It will involve building from source, instead of pip, at the moment; changing `build = False` to `build = True` in setup.py will activate the local compilation process. Then use `python setup.py [build install | develop]` and that should eliminate any library issues (libstdc++.so.6 incompatibility, for example).

@kalebsm , if you want to try to source install instead of pip, we will leave this issue open until we get the install instructions done, and it would be great to hear if the process described here works for you.

**Comment by dbhart** [comment]
Also, if you have SWIG, you can change `use_swig = False` to `use_swig = True` to compile using SWIG. I am not sure if that is faster, or not - @michaelbynum ?

**Comment by michaelbynum** [comment]
I recommend leaving `use_swig = False`. This flag only needs changed if the swig wrappers need updated, which is only needed if the c++ code changes.

**Comment by kalebsm** [comment]
@michaelbynum, sorry for the delay. I was using virtualenv to create a virtual environment, and pip to install packages. These are python specific and won't get any non-python dependencies. Utilizing conda does work, though also on an Ubuntu OS, virtualenv and pip do work to install pip and import wntr in a venv. The output from the original python console is as below:

Python 3.6.3 (default, Jan  4 2018, 16:40:53)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

And thank you @dbhart, when I am working on the original OS I will modify setup.py to eliminate the library issues from installing using pip.

**Comment by michaelbynum** [comment]
If installing with pip does not work, I recommend installing with conda. If conda is not an option, you can always clone the repo and build the package manually. You will just need a compiler. All you need to do is modify `setup.py` and set `build = True`. Then run `python setup.py install`.

**Comment by kalebsm** [comment]
Thanks Michael, I am finally attempting to figure this particular problem out. Sorry for the confusion, I forgot about dbhart comment about leaving this issue open, and had moved on to use wntr in a different environment. Now I am trying again to get it working in this linux environment.

To continue based on your comments regarding setup.py:

I modified setup.py and set build = True, then ran the command you recommend. I get the following traceback: 
![image](https://user-images.githubusercontent.com/56654036/90062539-d214ef00-dcb5-11ea-9d51-66f698fa5e6b.png)

Maybe I am misunderstanding the need for a compiler. Would you explain that a bit more? Additionally, if I want to set this up in a virtual environment, where should I save the WNTR-master file?

**Comment by Jay1109shah** [comment]
@michaelbynum still getting the same error ModuleNotFoundError: No module named 'wntr.sim.aml._evaluator'
I installed WNTR with conda

**Comment by kaklise** [comment]
The latest WNTR release (0.3.1) include support for Python 3.9.  If you are using that version of Python, this should resolve the _evaluator error.
