### ISSUE TITLE
AttributeError: 'numpy.float64' object has no attribute 'last_node'

### ISSUE THREAD

**Issue by jwlevis** [USEPA/WNTR#160]
I am trying to simulate a system using the WNTRSimulator.

My .inp file works in EPANET and using the EpanetSimulator in WNTR.

However, when I run it with the WNTRSimulator, I get the following warnings and error:
```
C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\network\elements.py:688: RuntimeWarning: overflow encountered in double_scalars
  eq_array = [H_1 - x[0] + x[1]*Q_1**x[2],
C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\network\elements.py:689: RuntimeWarning: overflow encountered in double_scalars
  H_2 - x[0] + x[1]*Q_2**x[2],
C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\network\elements.py:690: RuntimeWarning: overflow encountered in double_scalars
  H_3 - x[0] + x[1]*Q_3**x[2]]
C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\optimize\minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):

  File "C:\Users\Desktop\WNTR Demo Debug\cut_wntr_demo.py", line 29, in <module>
    results = sim.run_sim()

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\sim\core.py", line 818, in run_sim
    self._model, self._model_updater = wntr.sim.hydraulics.create_hydraulic_model(wn=self._wn, mode=self.mode, HW_approx=HW_approx)

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\sim\hydraulics.py", line 84, in create_hydraulic_model
    constraint.head_pump_headloss_constraint.build(m, wn, model_updater)

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\sim\models\constraint.py", line 318, in build
    con.add_condition(aml.inequality(body=f, ub=q_bar), m.pump_slope*(f - q_bar) + h_bar - end_h + start_h)

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\sim\aml\expr.py", line 1066, in inequality
    body -= ub

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\sim\aml\expr.py", line 92, in __sub__
    return self._binary_operation_helper(other, SubtractOperator)

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\wntr\sim\aml\expr.py", line 223, in _binary_operation_helper
    new_operator = cls(self, other.last_node())

AttributeError: 'numpy.float64' object has no attribute 'last_node'
```

Here is the current code:
```
import wntr

inp_file = "demo_city4-wntr3.inp"    
wn = wntr.network.WaterNetworkModel(inp_file)

simulator = "WNTR"

# Simulate hydraulics
if simulator == "WNTR":
   sim = wntr.sim.WNTRSimulator(wn)
else:
   simulator = "EPA"
   sim = wntr.sim.EpanetSimulator(wn)
   
results = sim.run_sim()
```

**Comment by kaklise** [comment]
After reviewing the INP file from @jwlevis, I believe the curve fit error has been resolved on the dev branch.  However, the WNTRSimulator fits the multipoint curves to the same form as a 3-point curve and that is causing some discrepancies in the simulation results.  We'll continue to look into this issue, but recommend using the EpanetSimulator with PDD for this case.

**Comment by kaklise** [comment]
Since the original issue has been resolved - using an updated curve fitting function in WNTR - I will close this issue.  We are still investigating the specific network model that @jwlevis is working with to identify WNTRSimulator convergence issues.
